### ISSUE TITLE
Inline Keyboard, Callback_query not being called

### ISSUE THREAD

**Issue by shah-smit** [yagop/node-telegram-bot-api#306] opened 2017-03-22 17:16 UTC
It is amazing tool for NodeJS.

But I am stuck with in-line keyboard.

```
bot.onText(/(.+)$/, function (msg, match) {
    const opts = {
    reply_markup: {
      inline_keyboard: [
        [
          {
            text: 'Edit Text',
            callback_data: 'edit'
          }
        ]
      ]
    }
  };
  bot.sendMessage(msg.from.id, 'Original Text', opts);
});

bot.on("callback_query", function(callbackQuery) {
    // 'callbackQuery' is of type CallbackQuery
    console.log(callbackQuery);
});
```

Referring to the above code, `callback_query` is not executed upon clicking `Edit Text` inline-button

How can i solve this?

**Comment by reactSearch** [comment] 2017-03-25 16:37
Hey,

Maybe do it like this?
`bot.on("callback_query", function nameOfTheFunction(callbackQuery) {`
`   // do your stuff here`
`}`

**Comment by shah-smit** [comment] 2017-03-26 06:08
@reactSearch Thanks for the revert.

Nope, It isnt consol-ing anything. When I do it.


```
var Bot = require('node-telegram-bot-api');
var TelegramToken = '<TOKEN>';
const bot = new Bot(TelegramToken, {polling: true});
console.log('Bot started...')
var formattedAnswer = '';

bot.onText(/(.+)$/, function (msg, match) {
    const opts = {
    reply_markup: {
      inline_keyboard: [
        [
          {
            text: 'Edit Text',
            callback_data: 'edit'
          }
        ]
      ]
    }
  };
  bot.sendMessage(msg.from.id, 'Original Text', opts);
});

bot.on("callback_query", function onCallbackQuery(callbackQuery) {
    // 'callbackQuery' is of type CallbackQuery
    console.log("query: ",callbackQuery);
});
```

**Comment by luiguild** [comment] 2017-06-22 07:07
Any news about it?

**Comment by GochoMugo** [comment] 2017-06-22 11:11
Works for me.

![screenshot](https://user-images.githubusercontent.com/4707579/27431275-996b53c2-5754-11e7-9b73-20d3f6d2995a.png)

**Comment by luiguild** [comment] 2017-06-22 16:42
You can share your code @GochoMugo? I've tried do this, but without success... :/

**Comment by GochoMugo** [comment] 2017-06-22 18:22
```js
const TelegramBot = require("node-telegram-bot-api");
const bot = new TelegramBot(process.env.TELEGRAM_TOKEN, { polling: true });

bot.onText(/\/callbackquery/, (msg, match) => {
    bot.sendMessage(msg.chat.id, "Click a button won't you!", {
        "reply_markup": {
            "inline_keyboard": [
                [
                    {
                        text: "Click me!",
                        callback_data: "click",
                    },
                ],
            ],
        },
    });
});


bot.on("callback_query", (callbackQuery) => {
    const msg = callbackQuery.message;
    bot.answerCallbackQuery(callbackQuery.id)
        .then(() => bot.sendMessage(msg.chat.id, "You clicked!"));
});
```

**Comment by luiguild** [comment] 2017-06-22 20:18
![captura de tela 2017-06-22 as 17 15 37](https://user-images.githubusercontent.com/16566338/27453926-73f95f8e-576e-11e7-97ed-a47e74355fc3.png)

@GochoMugo I copy your code and put in my bot, when I clicked in the button, appears a 'waiting' icon and nothing happens... do you know why?

**Comment by luiguild** [comment] 2017-06-22 21:45
I found the problem, @GochoMugo... in my package.json I had "node-telegram-bot-api": "^0.21.1", changed the version and it's worked! Thanks!

**Comment by luiguild** [comment] 2017-06-22 21:50
But my problem now is get the callback going from 'keyboard' object and not only from 'inline_keyboard', it's other procedure? 🤔

**Comment by GochoMugo** [comment] 2017-06-23 11:07
Could you write a small demo of what you are trying to achieve? Code is usually more precise. :grinning:

**Comment by luiguild** [comment] 2017-07-02 01:19
telegramBot.onText(/\/match/, msg => {
    const opts = {
        reply_to_message_id: msg.message_id,
        reply_markup: JSON.stringify({
            keyboard: [
                ['Opt1'],
                ['Opt2']            ],
            one_time_keyboard: true,
            selective: true
        })
    }
    telegramBot.sendMessage(msg.chat.id, 'Select One', opts)
})

I need a callback when user choose the option on keyboard not on inline_keyboard...

**Comment by mnb3000** [comment] 2017-07-02 01:29
@luiguild When user presses a button on a regular keyboard they send a message with a text which is displayed on a keyboard. You just need to make 
```telegramBot.onText(/Opt1/, msg => {
    // Do whatever you need
}```

**Comment by luiguild** [comment] 2017-07-02 01:58
@mnb3000 but in this case anyone that send one message with the same content, the bot will execute the function 😨 

It's not possible using something like `callback_data: "Opt1",` that is used in inline keyboard?

**Comment by mnb3000** [comment] 2017-07-02 13:19
@luiguild nope, that's how regular keyboards work

**Comment by luiguild** [comment] 2017-07-02 22:50
So... Ok... I will try another approach... Thank you!! 😃

**Comment by luiguild** [comment] 2017-07-02 23:01
BTW, I think that this issue to be closed. Thank's! 🎉

**Comment by ravi72munde** [comment] 2017-07-14 20:00
@luiguild what version did you change it to? I'm facing a similar problem.

**Comment by GochoMugo** [comment] 2017-07-18 06:13
@ravi72munde I believe the latest version on npm already supports callback queries, etc.

---

OP has **not** reacted to any comments. I'll go ahead and assume the issue is resolved by @luiguild's solution [above](https://github.com/yagop/node-telegram-bot-api/issues/306#issuecomment-310511495). Thanks everyone. :+1: 

#ANS

**Closed by GochoMugo** 2017-07-18 06:13 UTC
Labels: sorry! my bad!

**Comment by rjhariprasath** [comment] 2020-03-04 10:58
> ```js
> const TelegramBot = require("node-telegram-bot-api");
> const bot = new TelegramBot(process.env.TELEGRAM_TOKEN, { polling: true });
> 
> bot.onText(/\/callbackquery/, (msg, match) => {
>     bot.sendMessage(msg.chat.id, "Click a button won't you!", {
>         "reply_markup": {
>             "inline_keyboard": [
>                 [
>                     {
>                         text: "Click me!",
>                         callback_data: "click",
>                     },
>                 ],
>             ],
>         },
>     });
> });
> 
> 
> bot.on("callback_query", (callbackQuery) => {
>     const msg = callbackQuery.message;
>     bot.answerCallbackQuery(callbackQuery.id)
>         .then(() => bot.sendMessage(msg.chat.id, "You clicked!"));
> });
> ```

IF not Click any buttons ,how many hours it will wait for response. suppose after 3 hours when i click  (Click me!)buttons ,what will happen, it will  work or not?
is this handle any time response?

**Comment by rezamasrori** [comment] 2020-07-08 13:18
@GochoMugo  
how to change text inline_keyboard whne onClick in item ?

**Comment by ShodiyevF** [comment] 2020-12-15 21:55
I need help, please help. How do I do that when the inline buttons are pressed 1, the bot has to drop another file, when the button is pressed 2, the bot has to drop another file

**Comment by ShodiyevF** [comment] 2020-12-15 21:55
I need help, please help. How do I do that when the inline buttons are pressed 1, the bot has to drop another file, when the button is pressed 2, the bot has to drop another file 
![image](https://user-images.githubusercontent.com/71442024/102277479-2e309e00-3f4a-11eb-9f12-2460eb9f09e4.png)

**Comment by ShodiyevF** [comment] 2020-12-15 22:01
@GochoMugo  I need help, please help. How do I do that when the inline buttons are pressed 1, the bot has to drop another file, when the button is pressed 2, the bot has to drop another file 
![Uploading image.png…]()

**Comment by rezamasrori** [comment] 2020-12-15 22:18
> @GochoMugo I need help, please help. How do I do that when the inline buttons are pressed 1, the bot has to drop another file, when the button is pressed 2, the bot has to drop another file

hi dear,
please check 
 name ---> callback_data
for example : 
after click button and change callback_data 
const item = callbackQuery.data;
use
switch- case
     please check this image  [image](https://uupload.ir/files/2l3y_screen_shot_1399-09-26_at_01.47.10.png)

**Comment by ShodiyevF** [comment] 2020-12-16 10:11
thank you dear but I could not find a definite solution 😊

> > @GochoMugo I need help, please help. How do I do that when the inline buttons are pressed 1, the bot has to drop another file, when the button is pressed 2, the bot has to drop another file
> 
> hi dear,
> please check
> name ---> callback_data
> for example :
> after click button and change callback_data
> const item = callbackQuery.data;
> use
> switch- case
> please check this image [image](https://uupload.ir/files/2l3y_screen_shot_1399-09-26_at_01.47.10.png)

thank you dear but I could not find a definite solution 😊

**Comment by ShodiyevF** [comment] 2020-12-17 12:02
@GochoMugo broooo plzzzz help me

**Comment by italoHonoratoSA** [comment] 2024-05-06 19:38
I had the same problem. This appears to be a persistent bug and has to do with development documentation. Let's see that this problem is old and independent of the language or code version. There are countless reports of people having this same problem.

One of the solutions is that the return from the inline keyboard has to be treated as text. For some it works and for others it doesn't.

I spent 2 days trying to solve this until the following code worked for me:


```const TelegramBot = require('node-telegram-bot-api');
const texts = require('./langs/en');

const token = 'xxxx';
const bot = new TelegramBot(token, { polling: true });

// User state mapping
const userStates = {};

const networkSelectionMessage = 'Select item:';
const networkButtons = [
    [{ text: 'Item 1', callback_data: 'item1' }],
    [{ text: 'Item 2', callback_data: 'item2' }],
    [{ text: 'Item 3', callback_data: 'item3' }],
];

// Handler para o comando /start
bot.onText(/\/start/, (msg) => {
    const chatId = msg.chat.id;
    console.log('Received /start command from user:', chatId);

    userStates[chatId] = 'register';
    bot.sendMessage(chatId, 'Clicked: /start', {
        reply_markup: {
            inline_keyboard: [
                [{ text: '-->', callback_data: 'register' }]
            ]
        }
    });
});


// Handler for callback buttons
bot.on('callback_query', (callbackQuery) => {
    const chatId = callbackQuery.message.chat.id;
    const action = callbackQuery.data;
    console.log('Received callback query:', action, 'from user:', chatId);

    switch (action) {
        case 'register':

            userStates[chatId] = 'network';
            bot.sendMessage(chatId, networkSelectionMessage, {
                reply_markup: {
                    inline_keyboard: networkButtons
                }
            });
            break;
        default:
            if (userStates[chatId] === 'network') {
                bot.sendMessage(chatId, `Selected "${action}"`);
                // Update user state
                userStates[chatId] = 'contract';
            }
            break;
    }
});


bot.on('message', (msg) => {
    const chatId = msg.chat.id;
    const currentState = userStates[chatId];

    // Checks if the user is in contract state
    if (currentState === 'contract') {
        const varTest = msg.text;
        console.log('Received:', chatId, ':', varTest);

        bot.sendMessage(chatId, `"${varTest}"`);
        
        delete userStates[chatId];
    } else {
         // Process the text message normally
         // Here you can add logic to process other text messages
    }
});

// Handler for text editing callback
bot.on("callback_query", function(callbackQuery) {
    console.log(callbackQuery);
});```
