### ISSUE TITLE
i got polling_error

### ISSUE THREAD

**Issue by MojtabaRazmi** [yagop/node-telegram-bot-api#696] opened 2019-01-23 16:57 UTC
how can i fix this error :
error: [polling_error] {"code":"EFATAL","message":"EFATAL: Error: getaddrinfo EAI_FAIL api.telegram.org api.telegram.org:443"}

my simple code :
const TelegramBot = require('node-telegram-bot-api');
const token = '***';
const bot = new TelegramBot(token, {polling: true});

bot.on('message', (msg) => {
    let Hi = "hi";
    if (msg.text.toString().toLowerCase().indexOf(Hi) === 0) {
        bot.sendMessage(msg.chat.id,"Hello dear user");
    }
});

**Comment by alexandercerutti** [comment] 2019-01-23 17:00
Insert in your code this:

```javascript
bot.on("polling_error", (msg) => console.log(msg));
```

It will give you more info about the error.

**Comment by MojtabaRazmi** [comment] 2019-01-24 07:31
> bot.on("polling_error", (msg) => console.log(msg));

i do this, but i cant resolve my problem yet

**Comment by alexandercerutti** [comment] 2019-01-24 07:42
Does this printed something?

**Comment by alexandercerutti** [comment] 2019-01-24 08:39
This error indicated the Github issue to read, the #319. Read it, it should have the answer to your problem.

**Comment by MojtabaRazmi** [comment] 2019-01-24 08:54
> This error indicated the Github issue to read, the #319. Read it, it should have the answer to your problem.

i was do it,
but i cant solve my problem?
what is your idea about it?
can you help me?

**Comment by alexandercerutti** [comment] 2019-01-24 08:56
Try to insert this above all the code:

```javascript
process.env.NTBA_FIX_319 = 1;

```

**Comment by MojtabaRazmi** [comment] 2019-01-24 09:39
> Try to insert this above all the code:
> 
> ```js
> process.env.NTBA_FIX_319 = 1;
> ```

i do it
but it not help me

**Comment by alexandercerutti** [comment] 2019-01-24 09:42
I don't know. Maybe @kamikazechaser knows better the reason or has some better ideas.

**Comment by MojtabaRazmi** [comment] 2019-01-24 14:22
@kamikazechaser
can you help me?

**Comment by MojtabaRazmi** [comment] 2019-01-24 15:26
@alexandercerutti

thank you so about for your help 
i solve this problem.
that reason was my country :)

in my country telegram was banned by gov. and i solve this problem by changing my IP

**Comment by alexandercerutti** [comment] 2019-01-24 15:27
Oh okay! Perfect! Please, close this issue as you resolved! @MojtabaRazmi :)

**Comment by saeedhei** [comment] 2019-01-24 17:44
For Iranian, You can use SOCKS5 proxy with the socks5-https-client lib. 

Example:

```js
const TelegramBot = require('node-telegram-bot-api')
const Agent = require('socks5-https-client/lib/Agent')

const bot = new TelegramBot(process.env.TELEGRAM_API_TOKEN, {
	polling: true,
	request: {
		agentClass: Agent,
		agentOptions: {
			socksHost: process.env.PROXY_SOCKS5_HOST,
			socksPort: parseInt(process.env.PROXY_SOCKS5_PORT),
			// If authorization is needed:
			// socksUsername: process.env.PROXY_SOCKS5_USERNAME,
			// socksPassword: process.env.PROXY_SOCKS5_PASSWORD
		}
	}
})
```

**Comment by MojtabaRazmi** [comment] 2019-01-26 13:35
> For Iranian, You can use SOCKS5 proxy with the socks5-https-client lib.
> 
> Example:
> 
> ```js
> const TelegramBot = require('node-telegram-bot-api')
> const Agent = require('socks5-https-client/lib/Agent')
> 
> const bot = new TelegramBot(process.env.TELEGRAM_API_TOKEN, {
> 	polling: true,
> 	request: {
> 		agentClass: Agent,
> 		agentOptions: {
> 			socksHost: process.env.PROXY_SOCKS5_HOST,
> 			socksPort: parseInt(process.env.PROXY_SOCKS5_PORT),
> 			// If authorization is needed:
> 			// socksUsername: process.env.PROXY_SOCKS5_USERNAME,
> 			// socksPassword: process.env.PROXY_SOCKS5_PASSWORD
> 		}
> 	}
> })
> ```

thank you
it is DONE!

**Closed** 2019-01-26 13:35 UTC

**Comment by dinfyru** [comment] 2019-03-13 07:30
Why it can not working?

**Comment by shohruxbek** [comment] 2020-04-13 18:16
Salom. agar siz joylagan hosting sizga **ssl sertifikat** bermagan bo'lsa shunday xatolik berayapdi.

**Comment by TrasherTravis** [comment] 2023-09-18 08:02
I was phasic this error when connecting through Wifi network. I just connected my device to my mobile phone hotspot, and the bot runs without this error. 😊

**Comment by TreeKisan** [comment] 2023-11-18 05:58
> I was facing this error when connecting through the Wifi network. I just connected my device to my mobile phone hotspot, and the bot runs without this error. 😊
Solved my problem . thanks

**Comment by kamalbuilds** [comment] 2024-07-24 08:23
@alexandercerutti I am getting this error

```
 RequestError: Error: getaddrinfo ENOTFOUND api.telegram.org
    at new RequestError (C:\Users\geniu\Desktop\hackonblocks\xfaucet\node_modules\request-promise-core\lib\errors.js:14:15)
    at plumbing.callback (C:\Users\geniu\Desktop\hackonblocks\xfaucet\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\geniu\Desktop\hackonblocks\xfaucet\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\geniu\Desktop\hackonblocks\xfaucet\node_modules\request\request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.onRequestError (C:\Users\geniu\Desktop\hackonblocks\xfaucet\node_modules\request\request.js:877:8)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EFATAL'
}
```

**Comment by adminEthan** [comment] 2025-04-19 06:16
> e

are you fix it ?

**Comment by shohruxbek** [comment] 2025-04-19 12:54
> [#696 (comment)](https://github.com/yagop/node-telegram-bot-api/issues/696#issuecomment-2247204833)
> 
> are you fix it ?

set an ssl certificate to the domain connected to the hosting or server. with this, try the methods on top if the problem is not solved

**Comment by adminEthan** [comment] 2025-04-22 09:36
https://github.com/yagop/node-telegram-bot-api/issues/696#issuecomment-2816696533
thanks 
I displayed this issue on the VS code, but it can run normally in CMD，It should be that VS Code is not properly configured

**Comment by danzznhh** [comment] 2025-05-26 07:21
hello, how to fix that?

RequestError: AggregateError
    at new RequestError (/home/container/node_modules/request-promise-core/lib/errors.js:14:15)
    at plumbing.callback (/home/container/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/container/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/container/node_modules/request/request.js:185:22)
    at Request.emit (node:events:519:28)
    at Request.onRequestError (/home/container/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EFATAL'
}
