### ISSUE TITLE
Listen To Channel

### ISSUE THREAD

**Issue by ph3l1x** [yagop/node-telegram-bot-api#489] opened 2018-01-03 23:13 UTC
How can I get this bot to join a specific channel and record messages from a specific person. I need the bot to do something specific when a specific person sends a message to a channel.

**Comment by DaniyalGeek** [comment] 2018-01-20 02:03
Do you got any solution for this?

**Comment by steamhammer** [comment] 2018-01-24 19:49
1. Disable privacy mode in bot (https://core.telegram.org/bots#privacy-mode)
2. Listen to all messages and filter them out by either `message.from.id` or `message.from.username`.

**Comment by dmitrypisanko** [comment] 2018-01-31 21:21
Strange, my bot is administrator of the channel, but he ie not receiving from channel. Private mode is disabled. 

Any idea why?

**Comment by saeedhei** [comment] 2018-01-31 21:49
Hi @dmitrypisanko , Remove your Bot and Add again.

**Comment by dmitrypisanko** [comment] 2018-01-31 22:56
https://github.com/saeedhei done it ten times. Nothing changes

**Comment by Roguyt** [comment] 2018-06-14 09:57
As of today, the issue is still here :(
Does anyone have found a solution to this problem ?

**Comment by stav** [comment] 2022-02-01 03:33
I used [GramJS](https://github.com/gram-js/gramjs) in my bot to do essentially [this](https://github.com/stav/xapi/blob/e0655656d6d28df4aadfb3d02acdd5618fab44c8/src/bot/telegrama/listen.ts#L62):

    TelegramClient().addEventHandler(handler, { chats: [1234567890] }) 

And with this my bot is able listen to channels that it is _NOT_ a member of. 

It would be nice to be able to do this with this library.

**Comment by perryraskin** [comment] 2022-03-15 02:07
> I used [GramJS](https://github.com/gram-js/gramjs) in my bot to do essentially [this](https://github.com/stav/xapi/blob/e0655656d6d28df4aadfb3d02acdd5618fab44c8/src/bot/telegrama/listen.ts#L62):
> 
> ```
> TelegramClient().addEventHandler(handler, { chats: [1234567890] }) 
> ```
> 
> And with this my bot is able listen to channels that it is _NOT_ a member of.
> 
> It would be nice to be able to do this with this library.

How would I get the chat ID of a specific channel?

**Comment by stav** [comment] 2022-03-15 21:44
@perryraskin if you have the invite link then view the channel in a web browser and the id will be in the url

**Comment by perryraskin** [comment] 2022-03-16 15:03
Found it - thanks @stav 

Is there a full example of this? I haven't been able to successfully get something working that listens to a Telegram channel, and logs each message.

I tried using the `GetHistory()` method with no luck. I get this error:

```
Error: Cannot send requests while disconnected. You need to call .connect()
```

My code:

```javascript
const client = new TelegramClient(session, apiId, apiHash, {});

(async function run() {
  const result = await client.invoke(
    new Api.messages.GetHistory({
      peer: new Api.InputPeerChannel({
        channel_id,
        access_hash,
      }),
      offsetId: 9291972,
      offsetDate: 5920558,
      addOffset: 7946814,
      limit: 8137102,
      maxId: 9480436,
      minId: 8804446,
      hash: 9358333,
    })
  );
  console.log(result); // prints the result
})();

```

**Closed** 2022-05-31 13:11 UTC

**Comment by danielperez9430** [comment] 2022-05-31 13:14
> I used [GramJS](https://github.com/gram-js/gramjs) in my bot to do essentially [this](https://github.com/stav/xapi/blob/e0655656d6d28df4aadfb3d02acdd5618fab44c8/src/bot/telegrama/listen.ts#L62):
> 
> ```
> TelegramClient().addEventHandler(handler, { chats: [1234567890] }) 
> ```
> 
> And with this my bot is able listen to channels that it is _NOT_ a member of.
> 
> It would be nice to be able to do this with this library.

This is not a Telegram Bot API feature, is a tg client that use MTProto API.

**Comment by azoirov** [comment] 2023-02-01 15:52
I found the available events to listen channel events: 
```
event:
            | 'channel_post'
            | 'edited_message'
            | 'edited_message_text'
            | 'edited_message_caption'
            | 'edited_channel_post'
            | 'edited_channel_post_text'
            | 'edited_channel_post_caption',
```

**Comment by f22hd** [comment] 2024-01-10 09:27
> I found the available events to listen channel events:
> 
> ```
> event:
>             | 'channel_post'
>             | 'edited_channel_post'
>             | 'edited_channel_post_text'
>             | 'edited_channel_post_caption',
> ```
> 
> we can use it via:
> 
> ```
> bot.on('channel_post', (message) => {...})
> ```

Thank you, worked with me.
