### ISSUE TITLE
Enabling promise cancellation unconditionally could easily break an app

### ISSUE THREAD

**Issue by MySidesTheyAreGone** [yagop/node-telegram-bot-api#263] opened 2017-01-22 09:59 UTC
I was wrong. This is hilarious.

**Comment by MySidesTheyAreGone** [comment] 2017-01-23 16:10
To clarify, since the bug was reopened and you intend to ingestigate this, you can't enable cancellation after promises have been made. You have to do it as soon as you require Bluebird. In my case, after I pulled my head out of my arse, it was easy and painless to enable cancellation in my own app during startup; therefore I closed the bug. 

What stumped me specifically for an hour or so was pure sillyness, it's not worth anybody's attention. But a salient fact may be that in my app dependencies are loaded on-demand depending on what features the user turns on, which is why by the time I required node-telegram-bot-api I already had promises running and everything went down in flames.

I don't know if you can make the entire feature optional or just the Promise.config call, or if it's better to simply mention in the docs that if one uses this library then they need to require it as early as possible or to turn cancellation on themselves.

It's also worth looking into Bluebird itself and the reasons why this feature is optional in the first place.

As far as I'm concerned, the problem doesn't exist.

And by the way, this module is great.

**Comment by GochoMugo** [comment] 2017-12-08 16:45
Marking this as duplicate of #319. Please proceed there for more information.

**Closed by GochoMugo** 2017-12-08 16:45 UTC
Labels: investigate
